[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"

# Allow reading files from the script directory
fs_permissions = [{ access = "read", path = "./script" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
